# Generated by Django 4.2.4 on 2023-08-29 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_commentprofilemed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentprofilemed',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_comments', to='users.profilemed'),
        ),
    ]
