# Generated by Django 4.2.4 on 2023-08-30 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_commentprofilemed_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profilemed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'doctor')},
            },
        ),
    ]
