# Generated by Django 4.2.4 on 2023-08-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_doctorvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemed',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
