# Generated by Django 4.2.4 on 2023-08-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profilemed_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemed',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
