# Generated by Django 4.2.4 on 2023-08-30 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profilemed_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemed',
            name='rating',
        ),
    ]
