# Generated by Django 4.2.4 on 2023-08-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_category_dis'),
        ('users', '0011_remove_profilemed_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemed',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='medical.category'),
        ),
    ]
