# Generated by Django 4.2.4 on 2023-09-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_commentprofilemed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentprofilemed',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
