# Generated by Django 4.2.4 on 2023-10-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profilemed_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemed',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemed',
            name='image_cert',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
