# Generated by Django 4.2.4 on 2023-10-26 06:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_profilemed_image_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemed',
            name='image_cert',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image'),
        ),
    ]
