# Generated by Django 4.2.4 on 2023-09-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_category_dis'),
        ('questions', '0007_remove_question_category_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='questions', to='medical.category'),
        ),
    ]
