# Generated by Django 4.2.4 on 2023-09-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_answervote'),
    ]

    operations = [
        migrations.AddField(
            model_name='answervote',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
