# Generated by Django 4.2.4 on 2023-09-13 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_answervote_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answervote',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_vote', to='questions.answer'),
        ),
    ]
