# Generated by Django 4.2.4 on 2023-09-15 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profilemed_rating'),
        ('questions', '0011_alter_answervote_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='med',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_med', to='users.profilemed'),
        ),
    ]
