# Generated by Django 4.2.4 on 2023-08-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dis',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
